# Generated by Django 5.2.4 on 2025-09-02 07:39

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='企业名称')),
                ('uscc', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='统一社会信用代码格式不正确', regex='^[0-9A-Z]{18}$')], verbose_name='统一社会信用代码')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('license_image', models.TextField(blank=True, null=True, verbose_name='营业执照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
                'db_table': 'company',
            },
        ),
    ]
